### ISSUE TITLE
Support EUR, CHF and GBP

### ISSUE THREAD

**Issue by richardtop** [m4rr/money_bot#1]
Please add support for the following currencies:EUR, CHF and GBP.

Usage could be, e.g:
1 m USD to EUR

**Comment by m4rr** [comment]
@richardtop done @ f4b60412d9a0ef6e842eecfc2b1cbdf9987d0273

**Comment by richardtop** [comment]
Doesn't work in all the cases... But thanks for the implementation!
![IMG_4297](https://user-images.githubusercontent.com/8013017/57907906-614f0f00-7887-11e9-8a0e-690b6b362006.PNG)

**Comment by m4rr** [comment]
@richardtop  yeah, only "to" is supported. let's collect here all the cases? 🙂

**Comment by richardtop** [comment]
@m4rr as an idea, there should be a list of all possible translations of "to" word in multiple languages. So far, only English and Russian are needed...

**Comment by m4rr** [comment]
text like `100 THB to SGD` — done 👌🏿

**Comment by richardtop** [comment]
![No way :) by richardtop](https://i.imgur.com/XUvnxv5.jpg)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
